server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/srqc_springboot?serverTimezone=CTT&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      max-idle: 10
      max-active: 50
      max-wait: 10000
      initial-size: 5
      default-transaction-isolation: 2
  #配置redis服务器
  redis:
    host: localhost
    port: 6379
    timeout: 3000
    #配置redis连接池
    jedis:
      pool:
        min-idle: 5
        max-wait: 2000
        max-active: 10
        max-idle: 5


mybatis:
  mapper-locations: classpath:mapping/*.xml
  configuration:
    map-underscore-to-camel-case: true
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl